"""Copy currently rendered by the home hero on https://mart.implesia.com/."""

BANNER_SLUG = "home"

BANNER_DEFAULTS = {
    "slug": BANNER_SLUG,
    "brand_name": "Implesia Mart",
    "aria_label": "ফিচার্ড প্রোডাক্ট",
    "trust_line": "সারাদেশে ক্যাশ অন ডেলিভারি · ৩ দিনের ইজি রিটার্ন",
    "previous_label": "আগের স্লাইড",
    "next_label": "পরের স্লাইড",
    "slide_label": "স্লাইড",
    "autoplay_delay_ms": 6500,
    "transition_speed_ms": 750,
    "pause_on_hover": True,
    "loop": True,
    "keyboard_enabled": True,
    "disable_on_interaction": False,
    "cross_fade": True,
}

SLIDE_DEFAULTS: list[dict[str, object]] = [
    {
        "slug": "sunset-rainbow-projection-lamp",
        "eyebrow": "বেস্ট সেলার গ্যাজেট",
        "title": "সানসেট ল্যাম্পে বদলে যাক রুমের মুড",
        "description": ("ওয়ার্ম প্রজেকশন লাইটে ঘর, ডেস্ক বা কনটেন্ট শট — এক ল্যাম্পেই প্রিমিয়াম অ্যামবিয়েন্স।"),
        "price": 999,
        "compare_at_price": 1499,
        "price_prefix": None,
        "primary_cta_label": "এখনই অর্ডার",
        "primary_cta_href": "/products/sunset-rainbow-projection-lamp",
        "secondary_cta_label": "সব গ্যাজেট",
        "secondary_cta_href": "/products",
        "image_src": "/images/products/lamp/lamp-5.jpg",
        "image_alt": "সানসেট প্রজেকশন ল্যাম্প",
        "accent": "gold",
        "sort_order": 0,
    },
    {
        "slug": "ai-face-tracking-phone-holder",
        "eyebrow": "নতুন অ্যাডিশন",
        "title": "AI ট্র্যাকিংয়ে একাই প্রো শুট",
        "description": "ফেস ট্র্যাকিং হোল্ডার আপনাকে ফ্রেমে রাখে — রিলস, ভ্লগ ও লাইভ এখন হাতমুক্ত।",
        "price": 1999,
        "compare_at_price": 2499,
        "price_prefix": None,
        "primary_cta_label": "অর্ডার করুন",
        "primary_cta_href": "/products/ai-face-tracking-phone-holder",
        "secondary_cta_label": "বিস্তারিত",
        "secondary_cta_href": "/products/ai-face-tracking-phone-holder",
        "image_src": "/images/products/selfie-stand/stand-1.jpg",
        "image_alt": "এআই ফেস ট্র্যাকিং সেলফি স্ট্যান্ড",
        "accent": "teal",
        "sort_order": 1,
    },
    {
        "slug": "custom-gorgeous-womens-gown",
        "eyebrow": "হাতে তৈরি ফ্যাশন",
        "title": "অনুষ্ঠানের জন্য কাস্টম গাউন",
        "description": ("মাপ ও ডিজাইন অনুযায়ী এমব্রয়ডারি গাউন — স্পেশাল ডে-তে নিজের লুক নিজেই নির্ধারণ করুন।"),
        "price": 15000,
        "compare_at_price": None,
        "price_prefix": "শুরু",
        "primary_cta_label": "কাস্টম অর্ডার",
        "primary_cta_href": "/products/custom-gorgeous-womens-gown",
        "secondary_cta_label": "সব ড্রেস",
        "secondary_cta_href": "/products",
        "image_src": "/images/products/baby-products/wedding-dress.jpeg",
        "image_alt": "হাতে তৈরি গর্জিয়াস উইমেন্স গাউন",
        "accent": "rose",
        "sort_order": 2,
    },
    {
        "slug": "custom-baby-party-frock",
        "eyebrow": "কাস্টম বেবি ওয়্যার",
        "title": "পার্টির জন্য বেবি ফ্রক",
        "description": "কালার, ডিটেইল ও মাপ কাস্টমাইজ করে হাতে তৈরি — ছোট্ট তারকার পার্টি লুক সম্পূর্ণ।",
        "price": 1450,
        "compare_at_price": None,
        "price_prefix": "শুরু",
        "primary_cta_label": "অর্ডার করুন",
        "primary_cta_href": "/products/custom-baby-party-frock",
        "secondary_cta_label": "যোগাযোগ",
        "secondary_cta_href": "/contact-us",
        "image_src": "/images/products/baby-products/baby-ground-frog-new.jpeg",
        "image_alt": "হাতে তৈরি বেবি পার্টি ফ্রক",
        "accent": "rose",
        "sort_order": 3,
    },
    {
        "slug": "slim-power-bank-10000mah",
        "eyebrow": "শীঘ্রই আসছে",
        "title": "স্লিম পাওয়ার ব্যাংক ১০,০০০mAh",
        "description": "হালকা ডিজাইন, ফাস্ট চার্জিং সাপোর্ট — দৈনন্দিন ব্যাটারি ব্যাকআপের স্মার্ট সমাধান।",
        "price": 1299,
        "compare_at_price": 1799,
        "price_prefix": None,
        "primary_cta_label": "প্রোডাক্ট দেখুন",
        "primary_cta_href": "/products/slim-power-bank-10000mah",
        "secondary_cta_label": "সব প্রোডাক্ট",
        "secondary_cta_href": "/products",
        "image_src": "/images/products/power-bank/power-bank.jpg",
        "image_alt": "স্লিম পাওয়ার ব্যাংক ১০,০০০mAh",
        "accent": "ink",
        "sort_order": 4,
    },
]
